# Numpy

Based on [this](https://www.dataquest.io/blog/numpy-cheat-sheet/)
and [cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

In [2]:
import numpy as np 

## Data Structures

### Data Structures

In [8]:
array = np.array([1,2,3,4,5],dtype="float")
matrix = np.array([[1, 2], [3, 4]],dtype=float)

print("Array:")
print(array)
print("Matrix:")
print(matrix)

Array:
[1. 2. 3. 4. 5.]
Matrix:
[[1. 2.]
 [3. 4.]]


### Series

In [3]:
print( "A serie from 0 to 10, every second number:" )
print( np.arange(0,10,2)  )
print( "Five number from 0 to 100:" )
print( np.linspace(0,100,5) )

A serie from 0 to 10, every second number:
[0 2 4 6 8]
Five number from 0 to 100:
[  0.  25.  50.  75. 100.]


## CRUD Operations

### Create

#### Initialize

In [4]:
print( "Zero-initialized matrix:" )
print( np.zeros((2,2)) )
print( "Ones-initialized matrix:" )
print( np.ones((2,2)) )
print( "Identity matrix:" )
print( np.eye(2) )
print( "Matrix initialized with 99:" )
print( np.full((2,2),99) )
print( "Matrix initialized with random numbers from 0 to 100:" )
print( np.random.randint(100,size=(2,2)) )

Zero-initialized matrix:
[[0. 0.]
 [0. 0.]]
Ones-initialized matrix:
[[1. 1.]
 [1. 1.]]
Identity matrix:
[[1. 0.]
 [0. 1.]]
Matrix initialized with 99:
[[99 99]
 [99 99]]
Matrix initialized with random numbers from 0 to 100:
[[63 12]
 [35 24]]


### Read

In [5]:
print("Given the matrix:")
print(matrix)
print("Access 0th row:")
print(matrix[0])
print("Element in row 0 and, column 1:")
print(matrix[0][1])
print("Element in row 0 and, column 1:")
print(matrix[0,1]) 

Given the matrix:
[[1. 2.]
 [3. 4.]]
Access 0th row:
[1. 2.]
Element in row 0 and, column 1:
2.0
Element in row 0 and, column 1:
2.0


### Update

In [6]:
print("Given the matrix:")
print(matrix)
print("Make a copy:")
matrix_cpy = matrix.copy()
print(matrix_cpy)

print("Change the element [1][0] to 10:")
matrix_cpy[1,0]=10
print(matrix_cpy)
print("Change the first row to [0, 0]:")
matrix_cpy[0]=[0, 0]
print(matrix_cpy)
print("The new matrix is different to the original:")
print(matrix)

Given the matrix:
[[1. 2.]
 [3. 4.]]
Make a copy:
[[1. 2.]
 [3. 4.]]
Change the element [1][0] to 10:
[[ 1.  2.]
 [10.  4.]]
Change the first row to [0, 0]:
[[ 0.  0.]
 [10.  4.]]
The new matrix is different to the original:
[[1. 2.]
 [3. 4.]]


### Delete

In [15]:
A = np.array([1,2,3,4,5,6,7,8,9])
print (A)
print ("Remove first element")
print (np.delete( A ,0) )
print ("The original array is not modified:")
print (A)

[1 2 3 4 5 6 7 8 9]
Remove first element
[2 3 4 5 6 7 8 9]
The original array is not modified:
[1 2 3 4 5 6 7 8 9]


In [9]:
M = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(M)
print("Remove the first row: ")
print( np.delete(M,0,axis=0) )
print("Remove the first column: ")
print( np.delete(M,0,axis=1) )
print ("The original matrix is not modified:")
print( M )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Remove the first row: 
[[4 5 6]
 [7 8 9]]
Remove the first column: 
[[2 3]
 [5 6]
 [8 9]]
The original matrix is not modified:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Block operations

### Subsets

In [23]:
print(A)
print("Filter elements that are above 5")
print(A[np.where(A > 5)])

print("Alternatively, use array of boolean as index:")
is_above_5 = A > 5
print(is_above_5)
print(A[is_above_5])

[1 2 3 4 5 6 7 8 9]
Filter elements that are above 5
[6 7 8 9]
Alternatively, use array of boolean as index
[False False False False False  True  True  True  True]
[6 7 8 9]


In [14]:
P = np.array([["Product 1", "default", 10],["Product 2", "default", 20],["Product 3", "sale", 30] ])
print(P)
print("Filter rows with second column as 'default' ")
print(P[P[:,1]=="default", :])
print("Filter rows with second column as 'default' and third equals 10")
print(P[(P[:,1]=="default" ) & ( P[:,2]=="10"),:])


[['Product 1' 'default' '10']
 ['Product 2' 'default' '20']
 ['Product 3' 'sale' '30']]
Filter rows with second column as 'default' 
[['Product 1' 'default' '10']
 ['Product 2' 'default' '20']]
Filter rows with second column as 'default' and third equals 10
[['Product 1' 'default' '10']]


### Aggregates

In [11]:
print (M)
print("Aggregate functions:")
np.min(M), np.max(M), np.sum(M), np.average(M)
print("Sum by column:")
print(np.sum(M,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Aggregate functions:
Sum by column:
[12 15 18]


## Math operations

### Element-wise

In [6]:
M1 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
M2 = np.array([9,8,7,6,5,4,3,2,1]).reshape(3,3)

print("Element-wise addition:")
print( np.add(M1,M2) )
print("Element-wise subtraction:")
print( np.subtract(M1,M2) )
print("Element-wise multiplication:")
print( np.multiply(M1,M2) )
print("Element-wise division:")
print( np.divide(M1,M2) )

Element-wise addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Element-wise subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Element-wise multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Element-wise division:
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


### Matrix operations

In [7]:
print("Matrix multiplication:")
print(M1.dot(M2))

Matrix multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
